# Generated by Django 5.0.6 on 2026-05-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="link",
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(default="Veb Loyiha", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="gradient_end",
            field=models.CharField(default="#99f2c8", max_length=20),
        ),
        migrations.AddField(
            model_name="project",
            name="gradient_start",
            field=models.CharField(default="#1f4037", max_length=20),
        ),
        migrations.AddField(
            model_name="project",
            name="icon_class",
            field=models.CharField(default="fas fa-laptop-code", max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(
                help_text="Vergul bilan ajratib yozing: Django, JS, Redis",
                max_length=300,
            ),
        ),
    ]
