# Generated by Django 5.0.6 on 2026-05-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_remove_project_link_project_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_path",
            field=models.CharField(
                blank=True,
                help_text="Masalan: image/rasm_nomi.png",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gradient_end",
            field=models.CharField(
                blank=True, default="#99f2c8", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gradient_start",
            field=models.CharField(
                blank=True, default="#1f4037", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="icon_class",
            field=models.CharField(
                blank=True, default="fas fa-laptop-code", max_length=50, null=True
            ),
        ),
    ]
