# Generated by Django 5.0.6 on 2026-05-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_contactmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="gradient_end",
        ),
        migrations.RemoveField(
            model_name="project",
            name="gradient_start",
        ),
        migrations.RemoveField(
            model_name="project",
            name="icon_class",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image_path",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.URLField(default="#"),
        ),
    ]
