# Generated by Django 5.0.6 on 2026-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_remove_project_gradient_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Mijoz Ismi"),
                ),
                ("project_brief", models.TextField(verbose_name="Loyiha haqida")),
                (
                    "estimated_price",
                    models.CharField(max_length=100, verbose_name="Taxminiy Narx"),
                ),
                ("chat_transcript", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
    ]
