# Generated by Django 5.0.6 on 2026-05-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_aiorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmessage",
            name="email",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="telegram",
            field=models.CharField(
                default="No Telegram",
                max_length=200,
                verbose_name="Telegram URL yoki Username",
            ),
            preserve_default=False,
        ),
    ]
